### ISSUE TITLE
[Findable] Create global search component

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/findable-ui#11]
#### Need
The Data Explorer will have the ability to call additional search APIs (outside of the standard facet/filter functionality), for example, calling a keyword search API, and then displaying the returned search results within the standard Data Explorer table UI.

#### Approach
* See [mocks](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=4593-31305&t=7MPMgB8o65tCSO9u-0).

**Comment by NoopDog** [comment]
Not required
