### ISSUE TITLE
[Findable] Implement search over all facets

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/findable-ui#13]
#### Depends On
- [x] [Search over all filters](https://github.com/clevercanary/cc-design/issues/29)

#### Approach
* See [mocks](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=4593-31759&t=liWB3wsspb9mec28-0).
* Add tracking of search event.

**Comment by NoopDog** [comment]
Complete!
