### ISSUE TITLE
[Findable] Feedback form

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/findable-ui#18]

**Comment by frano-m** [comment]
See https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=1160-20415&mode=dev

**Comment by frano-m** [comment]
See [mock](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/HCA-Data-Explorer?type=design&node-id=1160-19694&mode=design&t=CEUnaeeMYxV5MhHx-4) and [mock](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/HCA-Data-Explorer?type=design&node-id=1160-20415&mode=design&t=CEUnaeeMYxV5MhHx-4) and [mock](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/HCA-Data-Explorer?type=design&node-id=1165-27835&mode=design&t=CEUnaeeMYxV5MhHx-4) and [mobile mock](https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/HCA-Data-Explorer?type=design&node-id=1160-20929&mode=design&t=CEUnaeeMYxV5MhHx-4).

**Comment by frano-m** [comment]
Duplicate of https://github.com/clevercanary/data-explorer/issues/406
