### ISSUE TITLE
[Findable] Integrate logout

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/findable-ui#21]
Integrate existing logout component (`packages/data-explorer-ui/src/components/Layout/components/Header/components/ProfileComponent/components/AuthenticationMenu/authenticationMenu.tsx`) into AnVIL DX's header (`https://github.com/clevercanary/data-explorer/blob/main/packages/data-explorer-ui/src/components/Layout/components/Header/components/ProfileComponent/profileComponent.tsx#L20`). 

See mocks [here](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=3826-34496) and [here](https://www.figma.com/file/JOUDXkKfgivRNFdBsWDPEH/AnVIL-Data-Explorer?type=design&node-id=2802-27761&t=OhpiF0O54xuTK2BH-0).

Please also add the actual logout functionality. For now, remove all filters and hard refresh (and navigate) to `/explore`

**Comment by NoopDog** [comment]
complete
