### ISSUE TITLE
[Findable] Dismissible footer banner

### ISSUE THREAD

**Issue by MillenniumFalconMechanic** [DataBiosphere/findable-ui#34]
#### Depends On
- [x] https://github.com/clevercanary/cc-design/issues/48

**Comment by NoopDog** [comment]
Cookies: https://www.figma.com/file/i4uZsYkKAML9ivi2TIo6ug/HCA-Data-Explorer?type=design&node-id=1008%3A14845&mode=design&t=MRIhonEoy5CuAD2y-1
